name: Blog test and deploy
run-name: ${{ github.actor }} is testing and deploying blog
on:
  workflow_dispatch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: hexo clean
      - run: hexo g
