name: Blog test and deploy
run-name: ${{ github.actor }} is testing and deploying blog

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    
    env:
      ssh-prefix: ssh -o StrictHostKeyChecking=no ubuntu@13.40.196.20
      temp-dir: /home/ubuntu/blog
      prod-dir: /var/www/html/blog

    steps:
      - uses: actions/checkout@v3

      - name: Clean install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Deploy to remote server
        run: |
          mkdir ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          # scp -o StrictHostKeyChecking=no -r ./public ubuntu@13.40.196.20:${{ env.temp-dir }}
          
      - name: Replace production code
        run: |
          echo "testing"
          ${{ env.ssh-prefix }} 'diff -qr ${{ env.prod-dir }} ${{ env.temp-dir }} | diff.txt'
          echo "testing"
          # ${{ env.ssh-prefix }} 'diff -qr ${{ env.prod-dir }} ${{ env.temp-dir }} | awk "/${{ env.prod-dir }}/ {print substr($3, 1, length($3)-1)}" '
          # ${{ env.ssh-prefix }} 'sudo cp -r {{ env.temp-dir }}/* ${{ env.prod-dir }}' # copy new
          # ${{ env.ssh-prefix }} 'rm -r ${{ env.temp-dir }}' # delete temp


      
      

