name: Blog test and deploy
run-name: ${{ github.actor }} is testing and deploying blog

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clean install dependencies
        run: npm ci
      
      - name: Generate public folder
        run: npm run build

      - name: Deploy to remote server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir ~/.ssh/
          echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r ./public ubuntu@13.40.196.20:/home/ubuntu/test


# jobs:
#   Build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - run: ls

#       - name: Cache node modules
#         id: cache-npm
#         uses: actions/cache@v3
#         env:
#           cache-name: cache-node-modules
#         with:
#           path: ./
#           key: ${{ runner.os }}-build-${{ env.cache-name }}
#           restore-keys: |
#             ${{ runner.os }}-build-${{ env.cache-name }}-
#             ${{ runner.os }}-build-
#             ${{ runner.os }}-

#       - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
#         name: List the state of node modules
#         continue-on-error: true
#         run: npm list


#       - name: Clean install dependencies
#         run: npm ci
      
#       - name: Generate public folder
#         run: npm run build

#       - run: ls

#   Deploy:
#     needs: Build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/cache@v3
#         with:
#           path: ./
#           key: ${{ runner.os }}-build-${{ env.cache-name }}

#       - name: Deploy to remote server
#         env:
#           SSH_KEY: ${{ secrets.SSH_KEY }}
#         run: |
#           echo env.SSH_KEY > ~/.ssh/id_rsa
#           chmod 700 ~/.ssh/id_rsa
#           scp -o StrictHostKeyChecking=no -r ./public ubuntu@13.40.196.20:/home/ubuntu/test


    